#!/usr/bin/env node
/**
 * Derive the portal's generated pages from content/generated (pushed by the
 * nurama monorepo on every production release):
 *
 *   .generated/openapi/<tag>.json       one OpenAPI document per tag, holding only the
 *                                       components that tag references (keeps each API
 *                                       page's payload small; Fumadocs embeds the whole
 *                                       document it renders from)
 *   content/websocket/                  MDX pages from the AsyncAPI document
 *   content/sdk/                        MDX pages from the TypeDoc markdown + method index
 *   content/mcp/                        MDX pages from the MCP tool catalogue
 *   public/openapi.{json,yaml}, public/asyncapi.{json,yaml}, public/mcp-tools.json,
 *   public/manifest.json                 raw documents at stable URLs
 *
 * Runs before `next dev` and `next build` (predev/prebuild). Everything it writes is
 * gitignored; edit content/generated's producers in the monorepo or this script.
 */
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const GEN = path.join(root, 'content/generated');
const CONTENT = path.join(root, 'content');
const SPLIT = path.join(root, '.generated/openapi');
const PUBLIC = path.join(root, 'public');
const BASE = '/docs/reference';
const METHODS = ['get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'trace'];

// ---------------------------------------------------------------- helpers

const readJson = (p) => JSON.parse(fs.readFileSync(p, 'utf8'));
const write = (p, content) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content);
};
const rm = (p) => fs.rmSync(p, { recursive: true, force: true });
const slug = (s) =>
  String(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
const walkFiles = (dir) =>
  fs.existsSync(dir)
    ? fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
        const p = path.join(dir, e.name);
        return e.isDirectory() ? walkFiles(p) : [p];
      })
    : [];

const frontmatter = (o) =>
  `---\n${Object.entries(o)
    .filter(([, v]) => v !== undefined && v !== null && v !== '')
    .map(([k, v]) => `${k}: ${JSON.stringify(v)}`)
    .join('\n')}\n---\n\n`;
const GENERATED_NOTE = '{/* Generated by scripts/generate.mjs from content/generated. Do not edit. */}\n\n';

/** Escape the characters MDX would parse as JSX or expressions, keeping existing escapes. */
const escText = (s) => String(s ?? '').replace(/\\[<{}]|[<{}]/g, (m) => (m.length === 2 ? m : `\\${m}`));

/** escText for markdown: leaves fenced blocks and inline code untouched. */
const escMarkdown = (md) =>
  String(md ?? '')
    .split(/(```[\s\S]*?```|~~~[\s\S]*?~~~)/)
    .map((part, i) =>
      i % 2 === 1
        ? part
        : part
            .split(/(`+[^`\n]*`+)/)
            .map((seg, j) => (j % 2 === 1 ? seg : escText(seg)))
            .join(''),
    )
    .join('');

/** A GFM table cell: escaped, single-line, pipes escaped. */
const cell = (s) =>
  escMarkdown(String(s ?? ''))
    .replace(/\|/g, '\\|')
    .replace(/\s*\r?\n\s*/g, ' ')
    .trim();

/**
 * The AsyncAPI builder repeats an operation's description on its message summary,
 * message description and payload description. Drop exact repeats of prose
 * paragraphs within one page (tables, headings, code and callouts are left alone).
 */
const dedupeParagraphs = (mdx) => {
  const seen = new Set();
  const structural = /^(\||#|```|<|-|\*\*|\{\/\*|---)/;
  return mdx
    .split(/\n\n+/)
    .filter((para) => {
      const key = para.trim();
      if (!key || structural.test(key)) return true;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .join('\n\n');
};

const firstSentence = (s) => {
  const text = String(s ?? '').replace(/\s+/g, ' ').trim();
  const m = text.match(/^(.+?[.!?])(\s|$)/);
  return (m ? m[1] : text).slice(0, 200);
};

/** JSON-pointer resolver bound to a document. */
const pointer = (doc) => (ref) => {
  if (typeof ref !== 'string' || !ref.startsWith('#/')) return undefined;
  return ref
    .slice(2)
    .split('/')
    .map((seg) => seg.replace(/~1/g, '/').replace(/~0/g, '~'))
    .reduce((node, seg) => (node == null ? undefined : node[seg]), doc);
};

const refName = (ref) => String(ref).split('/').pop();

// ---------------------------------------------------------------- JSON schema -> markdown

const deref = (schema, resolve, seen = new Set()) => {
  if (!schema || typeof schema !== 'object') return schema || {};
  if (schema.$ref) {
    if (seen.has(schema.$ref)) return { description: `See ${refName(schema.$ref)}` };
    const target = resolve(schema.$ref);
    return target ? deref({ title: refName(schema.$ref), ...target }, resolve, new Set([...seen, schema.$ref])) : {};
  }
  if (Array.isArray(schema.allOf)) {
    const merged = { ...schema, properties: { ...(schema.properties || {}) }, required: [...(schema.required || [])] };
    delete merged.allOf;
    for (const part of schema.allOf) {
      const d = deref(part, resolve, seen);
      Object.assign(merged.properties, d.properties || {});
      merged.required.push(...(d.required || []));
      if (!merged.description && d.description) merged.description = d.description;
      if (!merged.type && d.type) merged.type = d.type;
    }
    if (!Object.keys(merged.properties).length) delete merged.properties;
    if (!merged.required.length) delete merged.required;
    return merged;
  }
  return schema;
};

const typeOf = (schema, resolve, depth = 0) => {
  if (!schema || typeof schema !== 'object') return 'any';
  if (schema.$ref) return refName(schema.$ref);
  if (depth > 4) return schema.type || 'object';
  if (Array.isArray(schema.allOf)) return schema.allOf.map((s) => typeOf(s, resolve, depth + 1)).join(' & ');
  const union = schema.oneOf || schema.anyOf;
  if (Array.isArray(union)) return union.map((s) => typeOf(s, resolve, depth + 1)).join(' | ');
  if (Array.isArray(schema.enum)) return schema.enum.map((v) => JSON.stringify(v)).join(' | ');
  if (schema.type === 'array') return `${typeOf(schema.items, resolve, depth + 1)}[]`;
  let t = Array.isArray(schema.type) ? schema.type.join(' | ') : schema.type || (schema.properties ? 'object' : 'any');
  if (schema.format) t += ` (${schema.format})`;
  if (schema.nullable) t += ' | null';
  return t;
};

const constraints = (s) => {
  const out = [];
  if (s.default !== undefined) out.push(`Default: \`${JSON.stringify(s.default)}\``);
  if (s.minimum !== undefined) out.push(`min ${s.minimum}`);
  if (s.maximum !== undefined) out.push(`max ${s.maximum}`);
  if (s.minLength !== undefined) out.push(`min length ${s.minLength}`);
  if (s.maxLength !== undefined) out.push(`max length ${s.maxLength}`);
  if (s.minItems !== undefined) out.push(`min items ${s.minItems}`);
  if (s.maxItems !== undefined) out.push(`max items ${s.maxItems}`);
  if (s.pattern) out.push(`pattern \`${s.pattern}\``);
  if (s.example !== undefined) out.push(`Example: \`${JSON.stringify(s.example)}\``);
  return out.join('. ');
};

const isStructured = (s) => s && (s.properties || s.oneOf || s.anyOf || (s.type === 'array' && s.items && typeof s.items === 'object'));

/**
 * Render a schema as markdown: a property table for objects, a variant list for unions,
 * with nested objects expanded (depth-limited) under bold labels so the TOC stays clean.
 */
const renderSchema = (schema, resolve, depth = 0, maxDepth = 3) => {
  const s = deref(schema, resolve);
  const out = [];
  if (depth === 0 && s.description) out.push(escMarkdown(s.description), '');
  if (s.properties) {
    const req = new Set(s.required || []);
    out.push('| Property | Type | Required | Description |', '| --- | --- | --- | --- |');
    for (const [k, v] of Object.entries(s.properties)) {
      const pv = deref(v, resolve);
      const desc = [pv.description, constraints(pv)].filter(Boolean).join(' ');
      out.push(`| \`${k}\` | \`${cell(typeOf(v, resolve))}\` | ${req.has(k) ? 'yes' : 'no'} | ${cell(desc)} |`);
    }
    out.push('');
    if (depth < maxDepth) {
      for (const [k, v] of Object.entries(s.properties)) {
        const pv = deref(v, resolve);
        const inner = pv.type === 'array' ? deref(pv.items, resolve) : pv;
        if (inner && (inner.properties || inner.oneOf || inner.anyOf)) {
          out.push(`**\`${k}\`**${pv.type === 'array' ? ' (items)' : ''}`, '', renderSchema(inner, resolve, depth + 1, maxDepth));
        }
      }
    }
  } else if (s.oneOf || s.anyOf) {
    const branches = s.oneOf || s.anyOf;
    out.push(`One of ${branches.length} variants:`, '');
    branches.forEach((b, i) => {
      const bd = deref(b, resolve);
      const label = bd.title || (b.$ref ? refName(b.$ref) : `Variant ${i + 1}`);
      out.push(`**${escText(label)}**${bd.description ? ` — ${escMarkdown(firstSentence(bd.description))}` : ''}`, '');
      if (depth < maxDepth && isStructured(bd)) out.push(renderSchema(bd, resolve, depth + 1, maxDepth));
      else out.push(`Type: \`${cell(typeOf(b, resolve))}\``, '');
    });
  } else if (s.type === 'array') {
    out.push(`Array of \`${cell(typeOf(s.items, resolve))}\`.`, '');
    const inner = deref(s.items, resolve);
    if (depth < maxDepth && isStructured(inner)) out.push(renderSchema(inner, resolve, depth + 1, maxDepth));
  } else {
    out.push(`Type: \`${cell(typeOf(s, resolve))}\`${constraints(s) ? `. ${constraints(s)}` : ''}`, '');
  }
  return out.join('\n');
};

// ---------------------------------------------------------------- OpenAPI: split per operation

/**
 * Fumadocs embeds the whole OpenAPI document an API page renders from into that page's
 * client payload, so the portal feeds it one document per operation: the operation, its
 * path-level parameters, the tag definition and only the components it references.
 * Pages are still grouped by tag (groupBy: 'tag' in lib/source.ts).
 */
const splitOpenApi = (doc) => {
  rm(SPLIT);
  const collectRefs = (node, into) => {
    if (Array.isArray(node)) return node.forEach((n) => collectRefs(n, into));
    if (!node || typeof node !== 'object') return;
    if (typeof node.$ref === 'string' && node.$ref.startsWith('#/components/')) into.push(node.$ref);
    for (const v of Object.values(node)) collectRefs(v, into);
  };
  const files = [];
  const tagCounts = new Map();
  for (const [p, item] of Object.entries(doc.paths || {})) {
    const pathLevel = Object.fromEntries(Object.entries(item).filter(([k]) => !METHODS.includes(k)));
    for (const [m, op] of Object.entries(item)) {
      if (!METHODS.includes(m)) continue;
      const tags = op.tags && op.tags.length ? op.tags : ['Other'];
      const sub = {
        openapi: doc.openapi,
        info: doc.info,
        servers: doc.servers,
        security: doc.security,
        tags: (doc.tags || []).filter((t) => tags.includes(t.name)),
        paths: { [p]: { ...pathLevel, [m]: op } },
        components: {},
      };
      const queue = [];
      collectRefs(sub.paths, queue);
      while (queue.length) {
        const ref = queue.pop();
        const [, , type, name] = ref.split('/');
        const target = doc.components && doc.components[type] && doc.components[type][name];
        if (!target) continue;
        sub.components[type] = sub.components[type] || {};
        if (sub.components[type][name]) continue;
        sub.components[type][name] = target;
        collectRefs(target, queue);
      }
      if (doc.components && doc.components.securitySchemes) sub.components.securitySchemes = doc.components.securitySchemes;
      const file = `${slug(tags[0])}/${op.operationId ? slug(op.operationId) : slug(`${m}-${p}`)}.json`;
      write(path.join(SPLIT, file), JSON.stringify(sub));
      files.push({ file, tag: tags[0], bytes: JSON.stringify(sub).length });
      for (const t of tags) tagCounts.set(t, (tagCounts.get(t) || 0) + 1);
    }
  }
  files.sort((a, b) => a.file.localeCompare(b.file));
  // Folder titles for the tag groups: the virtual pages only carry the tag slug, so the
  // docs collection supplies a meta.json per tag folder with the tag's display name.
  for (const dir of fs.readdirSync(path.join(CONTENT, 'api'), { withFileTypes: true })) {
    if (dir.isDirectory()) rm(path.join(CONTENT, 'api', dir.name));
  }
  for (const tag of tagCounts.keys()) {
    const def = (doc.tags || []).find((t) => t.name === tag) || {};
    write(path.join(CONTENT, 'api', slug(tag), 'meta.json'), `${JSON.stringify({ title: def['x-displayName'] || tag, pages: ['...'] }, null, 2)}\n`);
  }
  write(
    path.join(SPLIT, 'index.json'),
    `${JSON.stringify({ files: files.map((f) => f.file), tags: [...tagCounts.entries()].map(([tag, operations]) => ({ tag, operations })) }, null, 2)}\n`,
  );
  return files;
};

// ---------------------------------------------------------------- AsyncAPI -> MDX

const generateWebsocket = (a) => {
  const resolve = pointer(a);
  const dir = path.join(CONTENT, 'websocket');
  rm(dir);
  const messageOf = (ref) => {
    const name = refName(ref);
    let m = resolve(ref) || {};
    if (m.$ref) m = resolve(m.$ref) || {};
    return { name, ...m };
  };
  const ops = Object.entries(a.operations || {}).map(([id, op]) => ({
    id,
    ...op,
    channelId: refName(op.channel.$ref),
    msgs: (op.messages || []).map((r) => messageOf(r.$ref)),
  }));
  const envelopes = ops.filter((o) => o.msgs.length > 5);
  const events = ops.filter((o) => o.msgs.length <= 5);
  const notifications = new Map();
  for (const op of envelopes) for (const m of op.msgs.slice(1)) if (!notifications.has(m.name)) notifications.set(m.name, m);

  const direction = (op) => (op.action === 'send' ? 'client → server' : 'server → client');
  const eventUrl = (op) => `${BASE}/websocket/events/${slug(op.id)}`;
  const notificationUrl = (name) => `${BASE}/websocket/notifications/${slug(name)}`;

  // index
  const intro = String(a.info.description || '')
    .split(/\n\s*\n/)
    .filter((p) => !/websocket\.yml|buildAsyncApi|notifications\.js/.test(p))
    .join('\n\n');
  const index = [
    frontmatter({ title: 'WebSocket events', description: 'Real-time Socket.IO events: channels, event payloads and every notification type.' }),
    GENERATED_NOTE,
    escMarkdown(intro),
    '',
    '## Servers',
    '',
    '| Server | URL | Notes |',
    '| --- | --- | --- |',
    ...Object.entries(a.servers || {}).map(([id, s]) => `| \`${id}\` | \`${cell(`${s.protocol}://${s.host}${s.pathname || ''}`)}\` | ${cell(s.description)} |`),
    '',
    '## Channels',
    '',
    'Channels are Socket.IO namespaces. Connect a Socket.IO client to the namespace address; do not open a raw WebSocket.',
    '',
    ...Object.entries(a.channels || {}).flatMap(([id, c]) => [
      `### ${escText(c.title || id)}`,
      '',
      `Address: \`${cell(c.address)}\``,
      '',
      escMarkdown(c.summary || ''),
      '',
      escMarkdown(c.description || ''),
      '',
      ...(c.parameters
        ? ['| Parameter | Description |', '| --- | --- |', ...Object.entries(c.parameters).map(([k, v]) => `| \`${k}\` | ${cell(v.description)} |`), '']
        : []),
    ]),
    '## Events',
    '',
    '| Event | Direction | Channel | Summary |',
    '| --- | --- | --- | --- |',
    ...[...envelopes, ...events].map((op) => `| [${cell(op.title || op.id)}](${eventUrl(op)}) | ${direction(op)} | \`${op.channelId}\` | ${cell(op.summary)} |`),
    '',
    `## Notification types`,
    '',
    `${notifications.size} notification types are delivered inside the \`notification\` envelope. See [Notification types](${BASE}/websocket/notifications).`,
    '',
  ].join('\n');
  write(path.join(dir, 'index.mdx'), index);

  // event pages
  for (const op of [...envelopes, ...events]) {
    const isEnvelope = envelopes.includes(op);
    const body = [
      frontmatter({ title: op.title || op.id, description: firstSentence(op.summary || op.description) }),
      GENERATED_NOTE,
      `<Callout>${direction(op)} on the \`${op.channelId}\` channel${isEnvelope ? '' : `. Socket.IO event name: \`${escText(op.msgs[0]?.name || op.id)}\``}.</Callout>`,
      '',
      escMarkdown(op.summary || ''),
      '',
      escMarkdown(op.description || ''),
      '',
    ];
    if (isEnvelope) {
      const envelope = op.msgs[0];
      body.push(`## Envelope: \`${escText(envelope.name)}\``, '', escMarkdown(envelope.description || envelope.summary || ''), '');
      if (envelope.payload) body.push(renderSchema(envelope.payload, resolve), '');
      body.push('## Notification types', '', '| `type` | Summary |', '| --- | --- |');
      for (const m of op.msgs.slice(1)) body.push(`| [\`${m.name}\`](${notificationUrl(m.name)}) | ${cell(m.summary)} |`);
      body.push('');
    } else {
      for (const m of op.msgs) {
        body.push(`## Payload: \`${escText(m.name)}\``, '');
        if (m.summary && m.summary !== op.summary) body.push(escMarkdown(m.summary), '');
        if (m.description && m.description !== op.description) body.push(escMarkdown(m.description), '');
        body.push(m.payload ? renderSchema(m.payload, resolve) : '_No payload._', '');
      }
    }
    write(path.join(dir, 'events', `${slug(op.id)}.mdx`), dedupeParagraphs(body.join('\n')));
  }
  write(
    path.join(dir, 'events', 'meta.json'),
    `${JSON.stringify({ title: 'Events', pages: [...envelopes, ...events].map((op) => slug(op.id)) }, null, 2)}\n`,
  );

  // notification pages
  const notifIndex = [
    frontmatter({ title: 'Notification types', description: 'Every notification delivered inside the notification envelope, with its tokens and changes payload.' }),
    GENERATED_NOTE,
    'Each notification arrives as a `notification` socket event whose `type` names one of the entries below. Subscribe to `notification` on a channel and switch on `type`.',
    '',
    '| `type` | Summary |',
    '| --- | --- |',
    ...[...notifications.values()].map((m) => `| [\`${m.name}\`](${notificationUrl(m.name)}) | ${cell(m.summary)} |`),
    '',
  ].join('\n');
  write(path.join(dir, 'notifications', 'index.mdx'), notifIndex);
  for (const m of notifications.values()) {
    const body = [
      frontmatter({ title: m.name, description: firstSentence(m.summary || m.description) }),
      GENERATED_NOTE,
      `<Callout>Delivered as the \`notification\` socket event with \`type\` set to \`${escText(m.name)}\`.</Callout>`,
      '',
      escMarkdown(m.summary || ''),
      '',
      escMarkdown((m.description || '').replace(/\n\nDelivered as the `notification` socket event[^\n]*/g, '')),
      '',
      '## Payload',
      '',
      m.payload ? renderSchema(m.payload, resolve) : '_No payload._',
      '',
    ];
    write(path.join(dir, 'notifications', `${slug(m.name)}.mdx`), dedupeParagraphs(body.join('\n')));
  }
  write(
    path.join(dir, 'notifications', 'meta.json'),
    `${JSON.stringify({ title: 'Notification types', pages: ['index', ...[...notifications.keys()].map(slug)] }, null, 2)}\n`,
  );
  write(path.join(dir, 'meta.json'), `${JSON.stringify({ title: 'WebSocket events', pages: ['index', 'events', 'notifications'] }, null, 2)}\n`);
  return { events: events.length + envelopes.length, notifications: notifications.size };
};

// ---------------------------------------------------------------- TypeDoc markdown -> MDX

const rewriteMdLinks = (md, fromDir, base) =>
  md.replace(/\]\(([^)\s#]+\.md)(#[^)]*)?\)/g, (_m, target, hash) => {
    const abs = path.posix.normalize(path.posix.join(fromDir, target)).replace(/\.md$/, '');
    const url = abs === 'index' ? base : `${base}/${abs}`;
    return `](${url}${hash || ''})`;
  });

/** GFM splits table cells on `|` even inside inline code; TypeDoc does not escape those. */
const escapePipesInTableCode = (md) =>
  md
    .split('\n')
    .map((line) =>
      line.startsWith('|') ? line.replace(/`[^`\n]*`/g, (code) => code.replace(/\\\||\|/g, (m) => (m.length === 2 ? m : '\\|'))) : line,
    )
    .join('\n');

const mdToMdx = (input) => {
  const md = escapePipesInTableCode(input);
  const anchors = [];
  const protectedMd = md.replace(/<a id="[^"]*"><\/a>/g, (m) => {
    anchors.push(m);
    return `\u0001${anchors.length - 1}\u0001`;
  });
  return escMarkdown(protectedMd).replace(/\u0001(\d+)\u0001/g, (_m, i) => anchors[Number(i)]);
};

const generateSdk = () => {
  const src = path.join(GEN, 'sdk/reference');
  const dir = path.join(CONTENT, 'sdk');
  rm(dir);
  const modules = [];
  for (const file of walkFiles(src).filter((f) => f.endsWith('.md'))) {
    const rel = path.relative(src, file).replace(/\\/g, '/');
    if (rel === 'index.md') continue;
    let md = fs.readFileSync(file, 'utf8');
    const h1 = md.match(/^# (.+)$/m);
    const heading = h1 ? h1[1].trim() : rel.replace(/\.md$/, '');
    if (h1) md = md.slice(h1.index + h1[0].length);
    const out = rel.replace(/\.md$/, '');
    const isRoute = out.startsWith('routes/');
    const name = isRoute ? out.slice('routes/'.length) : heading;
    const title = isRoute ? `${name}` : heading;
    const description = isRoute
      ? `Methods and types of the \`${name}\` namespace (\`client.${name}\` / \`bot.${name}\`).`
      : `${heading} class reference.`;
    md = rewriteMdLinks(md, path.posix.dirname(rel), `${BASE}/sdk`);
    write(path.join(dir, `${out}.mdx`), `${frontmatter({ title, description })}${GENERATED_NOTE}${mdToMdx(md).trim()}\n`);
    modules.push({ out, name, isRoute });
  }

  // Curated method index (packages/sdk/AGENTS.md), minus the contributor-only tail.
  let mi = fs.readFileSync(path.join(GEN, 'sdk/method-index.md'), 'utf8');
  mi = mi.replace(/^# [^\n]*\n/, '');
  const cut = mi.search(/^## How this SDK is documented/m);
  if (cut > 0) mi = mi.slice(0, cut);
  mi = mi.replace(/> File: `packages\/sdk\/src\/routes\/([a-zA-Z]+)\.ts`/g, (_m, ns) => `> Reference: [${ns}](${BASE}/sdk/routes/${ns})`);
  write(
    path.join(dir, 'method-index.mdx'),
    `${frontmatter({ title: 'Method index', description: 'Task-oriented index of the bot-reachable SDK surface, with read/mutate flags and conventions.' })}${GENERATED_NOTE}${mdToMdx(mi).trim()}\n`,
  );

  const clients = modules.filter((m) => !m.isRoute).sort((a, b) => a.name.localeCompare(b.name));
  const routes = modules.filter((m) => m.isRoute).sort((a, b) => a.name.localeCompare(b.name));
  const index = [
    frontmatter({ title: 'SDK reference', description: 'Generated reference for @nurama/sdk: the two clients and every namespace.' }),
    GENERATED_NOTE,
    'Generated from the TypeScript sources of [`@nurama/sdk`](https://www.npmjs.com/package/@nurama/sdk). Start with the [method index](./sdk/method-index) for a task-oriented view, then use the namespace pages for signatures and types.',
    '',
    '## Clients',
    '',
    ...clients.map((m) => `- [${m.name}](${BASE}/sdk/${m.out})`),
    '',
    '## Namespaces',
    '',
    'Available on both clients as `client.<namespace>` / `bot.<namespace>`.',
    '',
    ...routes.map((m) => `- [\`${m.name}\`](${BASE}/sdk/${m.out})`),
    '',
  ].join('\n');
  write(path.join(dir, 'index.mdx'), index);
  write(
    path.join(dir, 'meta.json'),
    `${JSON.stringify({ title: 'SDK reference', pages: ['index', 'method-index', '---Clients---', ...clients.map((m) => m.out), '---Namespaces---', 'routes'] }, null, 2)}\n`,
  );
  write(path.join(dir, 'routes', 'meta.json'), `${JSON.stringify({ title: 'Namespaces', pages: routes.map((m) => m.name) }, null, 2)}\n`);
  return { modules: modules.length };
};

// ---------------------------------------------------------------- MCP catalogue -> MDX

const generateMcp = (tools) => {
  const dir = path.join(CONTENT, 'mcp');
  rm(dir);
  const sorted = [...tools].sort((a, b) => a.name.localeCompare(b.name));
  for (const t of sorted) {
    const resolve = pointer(t.inputSchema || {});
    const hasInput = t.inputSchema && t.inputSchema.properties && Object.keys(t.inputSchema.properties).length;
    const body = [
      frontmatter({ title: t.name, description: firstSentence(t.description) }),
      GENERATED_NOTE,
      t.mutating
        ? '<Callout type="warn">Mutating tool: it changes data in Nurama. Available only when the key carries the matching scope.</Callout>'
        : '<Callout>Read-only tool.</Callout>',
      '',
      escMarkdown(t.description),
      '',
      '## Input',
      '',
      hasInput ? renderSchema(t.inputSchema, resolve) : '_This tool takes no input._',
      '',
      '## JSON Schema',
      '',
      '```json',
      JSON.stringify(t.inputSchema || {}, null, 2),
      '```',
      '',
    ].join('\n');
    write(path.join(dir, `${t.name}.mdx`), body);
  }
  const index = [
    frontmatter({ title: 'MCP tools', description: `The ${sorted.length} tools the Nurama MCP server exposes, with their input schemas.` }),
    GENERATED_NOTE,
    'Every tool below is served by the Nurama MCP server (see the [MCP guide](/docs/guides/mcp) for setup). Tool names, descriptions and input schemas are exactly what the server returns from `tools/list`; the raw catalogue is available at [`/mcp-tools.json`](/mcp-tools.json).',
    '',
    '| Tool | Mutating | Summary |',
    '| --- | --- | --- |',
    ...sorted.map((t) => `| [\`${t.name}\`](${BASE}/mcp/${t.name}) | ${t.mutating ? 'yes' : 'no'} | ${cell(firstSentence(t.description))} |`),
    '',
  ].join('\n');
  write(path.join(dir, 'index.mdx'), index);
  write(path.join(dir, 'meta.json'), `${JSON.stringify({ title: 'MCP tools', pages: ['index', ...sorted.map((t) => t.name)] }, null, 2)}\n`);
  return { tools: sorted.length, mutating: sorted.filter((t) => t.mutating).length };
};

// ---------------------------------------------------------------- main

const main = () => {
  const openapi = readJson(path.join(GEN, 'api/openapi.json'));
  const asyncapi = readJson(path.join(GEN, 'api/asyncapi.json'));
  const tools = readJson(path.join(GEN, 'mcp/tools.json'));
  const manifest = fs.existsSync(path.join(GEN, 'manifest.json')) ? readJson(path.join(GEN, 'manifest.json')) : {};

  fs.mkdirSync(PUBLIC, { recursive: true });
  for (const f of ['openapi.json', 'openapi.yaml', 'asyncapi.json', 'asyncapi.yaml']) fs.copyFileSync(path.join(GEN, 'api', f), path.join(PUBLIC, f));
  fs.copyFileSync(path.join(GEN, 'mcp/tools.json'), path.join(PUBLIC, 'mcp-tools.json'));
  write(path.join(PUBLIC, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);

  const tags = splitOpenApi(openapi);
  const ws = generateWebsocket(asyncapi);
  const sdk = generateSdk();
  const mcp = generateMcp(tools);
  const largest = tags.reduce((a, b) => (b.bytes > a.bytes ? b : a), tags[0]);
  console.log(
    [
      `openapi: ${tags.length} operation documents (largest ${largest.file}: ${Math.round(largest.bytes / 1024)} KB)`,
      `websocket: ${ws.events} events, ${ws.notifications} notification types`,
      `sdk: ${sdk.modules} modules`,
      `mcp: ${mcp.tools} tools (${mcp.mutating} mutating)`,
      manifest.source ? `source: ${manifest.source.repository}@${String(manifest.source.commit).slice(0, 12)} (sdk ${manifest.versions?.sdk}, api ${manifest.versions?.api})` : '',
    ]
      .filter(Boolean)
      .join('\n'),
  );
};

main();
